name: Deploy to prod

on:
  push:
    branches:
      - master

jobs:
  deploy_to_live:
    name: Deploy prod hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install firebase tools
        run: npm install firebase-tools -g

      - name: install dependencies
        run: npm install
      
      - name: build production project
        run: npm run build

      - name: Run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}